### ISSUE TITLE
ps2 mode isnt working

### ISSUE THREAD

**Issue by Radeon91** [sd2psx/firmware#3] opened 2022-12-15 09:59 UTC
ps1 mode is working perfect on both consoles but ps2 mode isnt working on a ps2.
Console does not detect the card.

**Comment by xyzz** [comment] 2022-12-15 09:59
Did you install CIV from the menu?

**Comment by Radeon91** [comment] 2022-12-15 10:03
didnt know you have to do it, i will search for that file and will try it again, file must be at root of sd?

**Comment by xyzz** [comment] 2022-12-15 10:28
CIV is an initialization vector for the PS2 magicgate implementation. This is 8 bytes, you can find the value online but I cannot post it here since it's technically a sony secret. After you get these 8 bytes, put them in a hex editor to create a CIV.bin, place it to the root of microsd and select "Deploy CIV" from the menu, then the card should be detected in PS2 mode after a restart.

**Comment by Radeon91** [comment] 2022-12-15 10:39
only one question, that civ remains on the pico after installing it or must i do it on every microsd that i want to use?

**Comment by xyzz** [comment] 2022-12-15 10:46
It is installed to the onboard flash memory, so it will work with any microsd.

**Comment by Radeon91** [comment] 2022-12-15 10:47
IT WORKS, you're a genius

BTW, just tried to install a FMBC for fun and it works after second restar, on firts boot the card is still initializing but on second boot it works flaswless

**Comment by Radeon91** [comment] 2022-12-15 10:48
another thing is, there are any way to change the size of an PS2 mc?

**Comment by xyzz** [comment] 2022-12-15 11:38
It is limited to 8MB max due to the size of the PSRAM chip. Anyway, I'll close the issue now since the problem is resolved & I've now added an additional warning message to PS2 mode when there is no CIV deployed.

**Closed by xyzz** 2022-12-15 11:38 UTC
